# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-14 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_employee_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='created_date',
        ),
        migrations.AddField(
            model_name='employee',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='pictures/employees/%Y/%m/%d', verbose_name='\u0410\u0432\u0430\u0442\u0430\u0440'),
        ),
        migrations.AlterField(
            model_name='commentpicture',
            name='path',
            field=models.ImageField(upload_to='pictures/comments/%Y/%m/%d', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='taskpicture',
            name='path',
            field=models.ImageField(upload_to='pictures/tasks/%Y/%m/%d', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435'),
        ),
    ]
