# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-20 09:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20160114_2106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentpicture',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='taskpicture',
            name='task',
        ),
        migrations.DeleteModel(
            name='CommentPicture',
        ),
        migrations.DeleteModel(
            name='TaskPicture',
        ),
    ]
