# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-08 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_comment_commentpicture_taskpicture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentpicture',
            name='path',
            field=models.ImageField(upload_to='pictures/%Y/%m/%d', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='taskpicture',
            name='path',
            field=models.ImageField(upload_to='pictures/%Y/%m/%d', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435'),
        ),
    ]
