# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-08 21:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20160108_2338'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('created_date',)},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('created_date',)},
        ),
        migrations.RenameField(
            model_name='task',
            old_name='created',
            new_name='created_date',
        ),
        migrations.AddField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 1, 8, 21, 5, 59, 261535, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
