# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-09 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20160109_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[(0, '\u041d\u043e\u0432\u044b\u0439'), (1, '\u0412 \u043f\u0440\u043e\u0446\u0435\u0441\u0441\u0435'), (2, '\u0417\u0430\u0432\u0435\u0440\u0448\u0435\u043d\u043e'), (3, '\u041f\u0440\u043e\u0432\u0435\u0440\u0435\u043d\u043e')], default=0),
            preserve_default=False,
        ),
    ]
