# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-09 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20160109_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.PositiveSmallIntegerField(choices=[(0, '\u041d\u043e\u0432\u044b\u0439'), (1, '\u0412 \u043f\u0440\u043e\u0446\u0435\u0441\u0441\u0435'), (2, '\u0417\u0430\u0432\u0435\u0440\u0448\u0435\u043d\u043e'), (3, '\u041f\u0440\u043e\u0432\u0435\u0440\u0435\u043d\u043e')], default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, '\u041d\u0438\u0437\u043a\u0438\u0439'), (1, '\u0421\u0440\u0435\u0434\u043d\u0438\u0439'), (2, '\u0412\u044b\u0441\u043e\u043a\u0438\u0439')], default=0),
        ),
    ]
